### ISSUE TITLE
資料來源

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/ASR-no-Pangcah#3]
https://github.com/thewayiam/ami_dict_crawler

Mp3 ài ka-tī wget...

**Comment by miaoski** [comment]
Lia̍h hó͘-sè ah.  M̄-kó, MP3 kó-lêng ū pán-khoân. Tāi-khāi m̄-hó͘ upload.

**Comment by sih4sing5hong5** [comment]
Siūⁿ-siūⁿ--leh mài thoân hó--ah, án-ne choan-àn siuⁿ tōa pháiⁿ hōaⁿ.
Lán hō͘-siong chéng-lí tùi-hong ê scripts èng-kai khah lí-sióng.

miaoski <notifications@github.com> 於 2019年11月12日週二 下午10:45 寫道：
